name: Security Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write        
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: './application'
        format: 'table'

    - name: Build Docker image for scanning
      run: |
        docker build -f infrastructure/docker/Dockerfile -t nc-fttx-portal:scan ./application

    - name: Run Trivy container scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'nc-fttx-portal:scan'
        format: 'table'

    - name: Start application for DAST
      run: |
        docker run -d -p 8080:8080 --name test-app nc-fttx-portal:scan
        sleep 30

    - name: Run OWASP ZAP baseline scan
      id: zap-scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:8080'
        artifact_name: 'zap-baseline-report'  # custom report
      continue-on-error: true

    - name: Cleanup test container
      if: always()
      run: docker rm -f test-app

    - name: Notify Slack on security issues
      if: failure() || steps.zap-scan.outcome == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: "Security vulnerabilities detected in nc-fttx-portal"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}